In [4]:
!pip install numpy

  Using cached numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)



[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

### Create a 3x3 array with random integers between 1 and 100. Write a program to
"normalize" the array so that the values are scaled between 0 and 1.
Formula: (x - min) / (max - min)
• Example Output: An array where the smallest value becomes 0.0 and the
largest becomes 1.0.

In [9]:
import numpy as np

def normalize_array(arr):
    min_val = np.min(arr)
    max_val = np.max(arr)
    normalized_arr = (arr - min_val) / (max_val - min_val)
    return normalized_arr

arr = normalize_array(np.random.randint(1, 101, (3, 3)))

print(f"new array: {arr}")


new array: [[1.         0.76190476 0.        ]
 [0.29761905 0.67857143 0.32142857]
 [0.35714286 0.96428571 0.6547619 ]]


### Create a 1D array of 10 random numbers. Ask the user for a value X Find the value
in the array that is closest to X
• Example Input: Array: [1, 5, 8, 12], X = 10
• Example Output: 8 or 12 (whichever is mathematically closer).

In [17]:
def random_closest_numbers(arr, x):
    diff = np.abs(arr - x)
    min_diff = diff.min()
    closest_nums = arr[diff == min_diff]  # كل الأرقام التي تساوي أقل فرق
    return closest_nums

arr = np.array([1, 5, 8, 12])
closest = random_closest_numbers(arr, 2)
print(f"closest numbers: {closest}")

closest numbers: [1]



### Write a NumPy program to create a 5x5 array with random values. For each column
in the array, find the second-largest value.
• Example Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
• Example Output: [4, 5, 6] (These are the second-highest values for each
respective column).

In [20]:
def secound_largest_arr(arr):
    sorted_arr = np.sort(arr, axis=0)  # ترتيب كل عمود
    second_largest = sorted_arr[-2, :]  # الحصول على ثاني أكبر قيمة في كل عمود
    return second_largest
arr = secound_largest_arr(np.array([[1, 2, 3], [9,9,9], [7, 8, 9]]))
print(f"second largest: {arr}")

second largest: [7 8 9]


In [25]:
n = np.array([[1, 2, 3], [9,9,9], [7, 8, 9]])
n = np.sort(n, axis=0)
print(f"sorted: {n}")

sorted: [[1 2 3]
 [7 8 9]
 [9 9 9]]


### Create a 6x4 matrix of random integers. Identify which rows have a sum that is an
even number. Print the indices of these rows.

In [5]:
def summ_even_arr_nums(arr):
    row_sums = arr.sum(axis=1)
    even_rows = np.where(row_sums % 2 == 0)[0]
    return even_rows
print(f"even rows: {summ_even_arr_nums(np.array([[1, 2, 3], [9,9,9], [7, 8, 9]]))}")

even rows: [0 2]


### Create a 1D array of 30 random integers between 1 and 50. Replace all numbers that are multiples of 3 or 5 with the value -1.

In [ ]:

def replace_multiples():
    arr = np.random.randint(1, 51, 30)
    mask = (arr % 3 == 0) | (arr % 5 == 0)
    print(f"mask: {mask}")
    arr[mask] = -1
    return arr
replace_multiples()


### Write a NumPy program to create a 3x3 array with random values. For each row,
calculate its mean (average) and subtract that mean from every element in that
specific row.

In [90]:
def center_rows():
    arr = np.random.randint(20, 30, (3, 3)) 
    row_means = arr.mean(axis=1)
    centered_arr = arr - row_means
    return centered_arr
print(f"centered array: {center_rows()}")

centered array: [[ 0.66666667 -0.33333333 -0.66666667]
 [ 1.66666667 -1.33333333 -6.66666667]
 [-0.33333333  5.66666667  1.33333333]]
